Sprint 3
agodlevskii/go-url-shortener pull request #16
Opened 2022-07-01 16:00 UTC by agodlevskii

**Sprint 3: Database, errors**

**Changes:**
* Implement the AES encoding functionality.
* Implement the auth-related middleware to take care of the user-related cookie.
* Adjust the existing storage functionality to store the data in dependence of user.
* Implement a new endpoint that returns all URLs generated by the user.
* Expand the application config with a DB connection URL.
* Implement a separate route that pings the DB and reports its status.
* Implement the PostgreSQL storage.
* Implement a batch operation for all types of storage.
* Adjust the storage functionality to return the existing ID for the duplicate URL.
* Create a separate package for middlewares.
* Implement shared unit-test cases for all type of storages.
* Code refactoring.

2022-07-04 16:22 UTC, sergeysergeevru requested changes
Привет) Может уже писал, но вообще мне нравится аккуратность кода и его логическое разбиение. Приятно проверять. Есть несколько вещей которые можно улучшить, комментарии оставил. Спасибо!)

2022-07-04 18:36 UTC, agodlevskii commented on internal/storage/file.go
> +		if data[2] == userID {
Я выше проверяю на то, что длина результирующего слайса должна быть равна трем. По идее, этого достаточно, чтобы обеспечить индексы 0, 1 и 2, даже если они будут пустые. Или есть какие-то эдж-кейсы?

2022-07-04 19:39 UTC, agodlevskii commented on internal/storage/db.go
> +			if err.Error() == "sql: no rows in result set" {
Почему-то у меня таким образом не отхватывает ошибку.
К тому же, если я сделаю по примеру из прикрепленной ссылки, я привяжу имплементацию к конкретному коннектору. Получается, имплементация будет уже не такая переиспользуемая? И если да, есть ли смысл тогда работать напрямую через pgx без встроенного sql-пакета?

2022-07-05 15:35 UTC, agodlevskii commented on internal/storage/memo.go
> +func (m MemoRepo) Add(userID string, batch map[string]string) (map[string]string, error) {
Имеет смысл об этом беспокоиться с самого начала, когда создается самая первая имплементация репозитория) Чем дольше висит этот рефакторинг, тем сложнее и рискованнее его впоследствии проводить

2022-07-07 15:50 UTC, sergeysergeevru commented on internal/storage/file.go
> +		if data[2] == userID {
ок, видимо просмотрел момент)

2022-07-07 16:18 UTC, sergeysergeevru approved these changes
Белиссимо! С моей точки зрения выглядит круто! Спасибо)

2022-07-07 16:18 UTC, sergeysergeevru commented on internal/storage/memo_test.go
> +			t.Parallel()
👍

2022-07-07 16:18 UTC, sergeysergeevru commented on internal/storage/memo.go
> +	})
можно просто создать новый инстанс синкмапы и присвоить m.db. А старый инстанс полностью удалить GC

2022-07-07 16:18 UTC, sergeysergeevru commented on internal/storage/file_test.go
> +			repo.Clear()
там где у тебя на каждый новый тест кейс создается новый инстанс репо то удалять все данные уже бессмысленно: так как на следующей итерации тест кейс опять создаст новый инстанс, а с точки зрения очистки памяти прибьет GC, ему в любом случае удалять старый экземплар, если он больше не используется.

2022-07-07 16:18 UTC, sergeysergeevru commented on internal/storage/file.go
> +	_, err := os.Stat(f.filename)
интересное прочтение пинга для файлового стораджа. Имеет место быть)

2022-07-11 14:33 UTC, merged